# Generated by Django 3.1 on 2020-08-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(default='this is the description')),
                ('price', models.TextField(default='200')),
                ('summary', models.TextField(default='this is cool!')),
            ],
        ),
    ]
