# Generated by Django 3.1 on 2020-08-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='this is the description'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default='200'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(default='producto name'),
        ),
    ]
